import { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { buildReport } from '../lib/reportGenerator'

const ALL_PANELS = buildReport([]).panels

const PRIORITY_LABEL = {
  1: { tag: 'CORE',     bg: '#fee2e2', color: '#dc2626' },
  2: { tag: 'ADVANCED', bg: '#f5f3ff', color: '#7c3aed' },
  3: { tag: 'PREMIUM',  bg: '#fdf4ff', color: '#9333ea' },
}

function ComingSoonToast({ onClose }) {
  return (
    <div style={{
      position: 'fixed', bottom: 80, left: '50%', transform: 'translateX(-50%)',
      background: '#0f172a', color: '#fff', borderRadius: 14, padding: '14px 22px',
      fontSize: 14, fontWeight: 600, zIndex: 999, textAlign: 'center',
      boxShadow: '0 8px 32px rgba(0,0,0,0.3)', maxWidth: 320, width: '90%',
    }}>
      <div style={{ fontSize: 22, marginBottom: 4 }}>🚧</div>
      <div>Home collection booking is <span style={{ color: '#14b8a6' }}>coming soon</span>.</div>
      <div style={{ fontSize: 12, color: '#94a3b8', marginTop: 4 }}>
        Download or share the test list below and walk into any nearby diagnostic center to get tested today.
      </div>
      <button onClick={onClose} style={{ marginTop: 10, background: '#14b8a6', border: 'none', color: '#fff', borderRadius: 8, padding: '7px 18px', fontSize: 13, fontWeight: 700, cursor: 'pointer' }}>
        Got it
      </button>
    </div>
  )
}

export default function LabDoorstepScreen() {
  const nav = useNavigate()
  const [expandedPanel, setExpandedPanel] = useState(null)
  const [selectedPanels, setSelectedPanels] = useState(
    new Set(ALL_PANELS.filter(p => p.priority === 1).map(p => p.id))
  )
  const [showToast, setShowToast] = useState(false)
  const [copied, setCopied]       = useState(false)

  const chosen     = ALL_PANELS.filter(p => selectedPanels.has(p.id))
  const totalTests = chosen.reduce((s, p) => s + p.tests.length, 0)

  function togglePanel(id) {
    setSelectedPanels(prev => {
      const next = new Set(prev)
      next.has(id) ? next.delete(id) : next.add(id)
      return next
    })
  }

  function buildTestListText() {
    const lines = [
      'AROGYOS — BioAge Test Parameters',
      '=================================',
      'Take this list to any diagnostic center near you.',
      '',
    ]
    chosen.forEach(p => {
      lines.push(`${p.icon} ${p.name.toUpperCase()}`)
      lines.push(`   ${p.fasting ? 'Fasting required (10–12 hrs)' : 'No fasting required'} · ${p.sampleType}`)
      p.tests.forEach(t => lines.push(`   • ${t.name}  [${t.code}]`))
      lines.push('')
    })
    lines.push(`Total: ${totalTests} tests across ${chosen.length} panels`)
    lines.push('')
    lines.push('Generated by AROGYOS — your biological age app')
    lines.push('https://arogyos.com')
    return lines.join('\n')
  }

  function downloadList() {
    const text = buildTestListText()
    const blob = new Blob([text], { type: 'text/plain' })
    const url  = URL.createObjectURL(blob)
    const a    = document.createElement('a')
    a.href     = url
    a.download = 'AROGYOS_Test_Parameters.txt'
    a.click()
    URL.revokeObjectURL(url)
  }

  function shareOnWhatsApp() {
    const text = encodeURIComponent(buildTestListText())
    window.open(`https://wa.me/?text=${text}`, '_blank')
  }

  async function copyList() {
    try {
      await navigator.clipboard.writeText(buildTestListText())
      setCopied(true)
      setTimeout(() => setCopied(false), 2500)
    } catch {
      downloadList()
    }
  }

  return (
    <div className="ld-root">

      {showToast && <ComingSoonToast onClose={() => setShowToast(false)} />}

      {/* Medical disclaimer */}
      <div className="ld-edu-banner">
        ⚕️ <strong>For educational awareness.</strong> This is a suggested parameter guide to discuss with your doctor — not a medical prescription. Always consult your doctor before ordering tests.
      </div>

      {/* Top bar */}
      <div className="ld-topbar">
        <button className="ld-back" onClick={() => nav('/upload')}>← Back</button>
        <span className="ld-topbar-title">Lab at Your Doorstep</span>
        <span className="ld-topbar-badge">Coming soon</span>
      </div>

      {/* Hero */}
      <div className="ld-hero">
        <div className="ld-hero-icon">🏠🔬</div>
        <div className="ld-hero-title">Home Sample Collection</div>
        <div className="ld-hero-sub">
          A certified phlebotomist visits your home · collects blood samples · results uploaded directly to your AROGYOS BioAge score
        </div>
        <div className="ld-hero-stats">
          <div className="ld-stat"><span className="ld-stat-n">30 min</span><span className="ld-stat-l">Visit time</span></div>
          <div className="ld-stat-div"/>
          <div className="ld-stat"><span className="ld-stat-n">5–8</span><span className="ld-stat-l">Tubes drawn</span></div>
          <div className="ld-stat-div"/>
          <div className="ld-stat"><span className="ld-stat-n">24–48 h</span><span className="ld-stat-l">Results</span></div>
        </div>
      </div>

      {/* Coming soon notice */}
      <div style={{ background: 'linear-gradient(135deg,#0f3a3a,#0a2424)', borderRadius: 14, padding: '16px 18px', margin: '0 16px 20px', display: 'flex', gap: 12, alignItems: 'flex-start' }}>
        <div style={{ fontSize: 22 }}>🚧</div>
        <div>
          <div style={{ fontSize: 13, fontWeight: 700, color: '#fff', marginBottom: 4 }}>Home booking launching soon</div>
          <div style={{ fontSize: 12, color: 'rgba(255,255,255,0.6)', lineHeight: 1.5 }}>
            Until then — select your test panels below, then download or share the parameter list. Walk into any diagnostic center (SRL, Thyrocare, Redcliffe, local lab) and hand them this list.
          </div>
        </div>
      </div>

      {/* Panel selection */}
      <div className="ld-section-title">
        📋 Choose Your Test Panels
        <span className="ld-section-sub">{chosen.length} panel{chosen.length !== 1 ? 's' : ''} · {totalTests} tests selected</span>
      </div>

      {ALL_PANELS.map(panel => {
        const pri        = PRIORITY_LABEL[panel.priority]
        const isSelected = selectedPanels.has(panel.id)
        const isOpen     = expandedPanel === panel.id
        return (
          <div key={panel.id} className={`ld-panel ${isSelected ? 'ld-panel-on' : 'ld-panel-off'}`} style={{ borderLeftColor: panel.color }}>
            <div className="ld-panel-header">
              <label className="ld-panel-check">
                <input type="checkbox" checked={isSelected} onChange={() => togglePanel(panel.id)} />
                <span className="ld-checkmark" style={{ '--c': panel.color }} />
              </label>
              <div className="ld-panel-icon" style={{ background: `${panel.color}22`, color: panel.color }}>
                {panel.icon}
              </div>
              <div className="ld-panel-meta">
                <div className="ld-panel-name">{panel.name}</div>
                <div className="ld-panel-info">
                  <span className="ld-pri-tag" style={{ background: pri.bg, color: pri.color }}>{pri.tag}</span>
                  <span className="ld-panel-count">{panel.tests.length} tests</span>
                  {panel.fasting && <span style={{ fontSize: 10, color: '#d97706', fontWeight: 600 }}>🍽️ Fasting</span>}
                </div>
              </div>
              <button className="ld-expand-btn" onClick={() => setExpandedPanel(isOpen ? null : panel.id)}>
                {isOpen ? '▲' : '▼'}
              </button>
            </div>

            {isOpen && (
              <div className="ld-panel-body">
                <div className="ld-panel-why">{panel.whyCore}</div>
                <div className="ld-panel-sample">
                  <span className="ld-sample-tag">{panel.fasting ? '🍽️ Fasting required (10–12 hrs)' : '✓ No fasting needed'}</span>
                  <span className="ld-sample-type">{panel.sampleType}</span>
                </div>
                <div className="ld-test-list">
                  {panel.tests.map((t, i) => (
                    <div key={i} className="ld-test-row">
                      <span className="ld-test-dot" style={{ background: panel.color }} />
                      <span className="ld-test-name">{t.name}</span>
                      <span className="ld-test-code">{t.code}</span>
                    </div>
                  ))}
                </div>
              </div>
            )}
          </div>
        )
      })}

      {/* Action bar — share/download + coming soon book */}
      {chosen.length > 0 && (
        <div style={{ position: 'sticky', bottom: 72, background: '#fff', borderTop: '1px solid #e2e8f0', padding: '14px 16px', zIndex: 10 }}>
          <div style={{ fontSize: 12, color: '#64748b', marginBottom: 10, fontWeight: 600, textAlign: 'center' }}>
            {totalTests} tests selected · Share or download to apply at any local lab
          </div>
          <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 8, marginBottom: 8 }}>
            <button onClick={downloadList} style={{ padding: '12px 10px', background: '#f0fdf4', color: '#15803d', border: '1.5px solid #86efac', borderRadius: 10, fontSize: 13, fontWeight: 700, cursor: 'pointer' }}>
              ⬇️ Download List
            </button>
            <button onClick={shareOnWhatsApp} style={{ padding: '12px 10px', background: '#f0fdf4', color: '#15803d', border: '1.5px solid #86efac', borderRadius: 10, fontSize: 13, fontWeight: 700, cursor: 'pointer' }}>
              📲 Share on WhatsApp
            </button>
          </div>
          <button onClick={copyList} style={{ width: '100%', padding: '11px', background: '#f8fafc', color: '#64748b', border: '1.5px solid #e2e8f0', borderRadius: 10, fontSize: 13, fontWeight: 600, cursor: 'pointer', marginBottom: 8 }}>
            {copied ? '✅ Copied to clipboard!' : '📋 Copy test names'}
          </button>
          <button onClick={() => setShowToast(true)} style={{ width: '100%', padding: '14px', background: 'linear-gradient(90deg,#14b8a6,#059669)', color: '#fff', border: 'none', borderRadius: 12, fontSize: 14, fontWeight: 800, cursor: 'pointer', opacity: 0.6 }}>
            🏠 Book Home Collection — Coming Soon
          </button>
        </div>
      )}

      <div style={{ height: 200 }} />
    </div>
  )
}
